# Generated by Django 3.2.20 on 2023-08-18 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintask',
            old_name='username',
            new_name='fullname',
        ),
    ]
