# Generated by Django 3.2.20 on 2023-08-22 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintask',
            old_name='completed',
            new_name='ready',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='completed',
            new_name='ready',
        ),
        migrations.RenameField(
            model_name='subtask',
            old_name='completed',
            new_name='ready',
        ),
    ]
