# Generated by Django 3.2.20 on 2023-08-17 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_globaltask_subtasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globaltask',
            name='subtasks',
        ),
        migrations.AddField(
            model_name='subtask',
            name='relate_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.globaltask'),
        ),
    ]
